### ISSUE TITLE
How to move the numbering to the top?

### ISSUE THREAD

**Issue by 1cedsoda** [tingerrr/typst-anti-matter#2]

**Comment by tingerrr** [comment]
Please provide a description when posting an issue. I assume you meant how to display the numbering in the page header instead of the footer, but if you provided an example or description, I would know for sure.

You can do it like this:

```typst
#import "@preview/anti-matter:0.1.1": anti-matter, step, page-number

#show: anti-matter
#set page(header: step() + align(center, page-number()))

// ...
```

`step` is needed to ensure the correct number, `page-number` displays the current page number and numbering format.

[manual]: https://github.com/tingerrr/anti-matter/blob/main/docs/manual.pdf
